# Generated by Django 2.2.7 on 2020-02-21 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bootstrap4Column',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='bootstrap4_row_bootstrap4column', serialize=False, to='cms.CMSPlugin')),
                ('override_column_classes', models.TextField(verbose_name='class(переписать родительские)')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='Bootstrap4Row',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='bootstrap4_row_bootstrap4row', serialize=False, to='cms.CMSPlugin')),
                ('container_classes', models.TextField(default='container', help_text='container container-fluid', verbose_name='Container classes')),
                ('row_classes', models.TextField(default='row', help_text='row no-gutters', verbose_name='Row classes')),
                ('column_classes', models.TextField(default='col-lg-4', help_text='offset-lg-1 mx-lg-2 ', verbose_name='Column classes')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
    ]
