# Generated by Django 2.2.7 on 2020-02-21 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bootstrap4_row', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bootstrap4column',
            name='override_column_classes',
            field=models.TextField(blank=True, verbose_name='class(переписать родительские)'),
        ),
    ]
